ReplicatedSite/Models/Search/DistributorSearch.cs
using Common;
using Common.Api.ExigoOData;
using Common.Services;
using ReplicatedSite;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ReplicatedSite.Models
{
    public class DistributorSearch
    {
        [Display(Name = "Website Address"), DataType(DataType.Text), Required(ErrorMessage = "You Must Enter a Distributor's Site Name to Search by Website Address"), RegularExpression(GlobalSettings.RegularExpressions.LoginName)]
        public string WebAlias { get; set; }

        [Display(Name = "My Distributor's ID Is:"), DataType(DataType.Text), Required]
        public int DistributorID { get; set; }

        [Display(Name = "The Event ID Is:"), DataType(DataType.Text), Required]
        public int EventCode { get; set; }

        [Display(Name = "Distributor's First Name:*"), DataType(DataType.Text), Required(ErrorMessage = "Distributor's First Name is required")]
        public string DistributorFirstName { get; set; }
        [Display(Name = "Distributor's Last Name:*"), DataType(DataType.Text), Required(ErrorMessage = "Distributor's Last Name is required")]
        public string DistributorLastName { get; set; }
        [Display(Name = "Desiger's State:*"), Required(ErrorMessage = "Distributor's State is required")]
        public string DistributorState { get; set; }
        [Display(Name = "City: (optional)")]
        public string DistributorCity { get; set; }
        [Display(Name = "Zip Code: (optional)"), DataType(DataType.PostalCode)]
        public string DistributorZipCode { get; set; }
        public string Country { get; set; }
        public string AvatarUrl { get; set; }

        [Display(Name = "My Zip Code is:"), DataType(DataType.PostalCode), Required(ErrorMessage = "You Must Enter a Valid Zip Code to Search by Zip Code")]
        public string CustomerZipCode { get; set; }

        public SearchType SearchTypeID { get; set; }

        public List<CustomerSite> BaseQuery { get; set; }

    }
}

ReplicatedSite/Controllers/EnrollmentController.cs
using Common;
using Common.Api.ExigoWebService;
using Common.Providers;
using Common.HtmlHelpers;
using Common.Services;
using ExigoService;
using ReplicatedSite.Factories;
using ReplicatedSite.Models;
using ReplicatedSite.Providers;
using ReplicatedSite.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;

namespace ReplicatedSite.Controllers
{
    public class EnrollmentController : Controller
    {
        #region Constructor
        public EnrollmentController()
        {
            this.OrderConfiguration = Common.GlobalUtilities.GetMarketConfiguration(PropertyBag.SelectedMarket).Orders;
            this.AutoOrderConfiguration = Common.GlobalUtilities.GetMarketConfiguration(PropertyBag.SelectedMarket).AutoOrders;
            this.OrderPacksConfiguration = Common.GlobalUtilities.GetMarketConfiguration(PropertyBag.SelectedMarket).EnrollmentKits;
        }
        #endregion

        #region Properties
        public string ApplicationName = "BonveraEnrollment";

        public IOrderConfiguration OrderConfiguration { get; set; }
        public IOrderConfiguration AutoOrderConfiguration { get; set; }
        public IOrderConfiguration OrderPacksConfiguration { get; set; }

        public ShoppingCartItemsPropertyBag ShoppingCart
        {
            get
            {
                if (_shoppingCart == null)
                {
                    _shoppingCart = Exigo.PropertyBags.Get<ShoppingCartItemsPropertyBag>(ApplicationName + "Cart");
                }
                return _shoppingCart;
            }
        }
        private ShoppingCartItemsPropertyBag _shoppingCart;

        public EnrollmentPropertyBag PropertyBag
        {
            get
            {
                if (_propertyBag == null)
                {
                    _propertyBag = Exigo.PropertyBags.Get<EnrollmentPropertyBag>(ApplicationName + "PropertyBag");
                }
                return _propertyBag;
            }
        }
        private EnrollmentPropertyBag _propertyBag;

        public ILogicProvider LogicProvider
        {
            get
            {
                if (_logicProvider == null)
                {
                    _logicProvider = new EnrollmentLogicProvider(this, ShoppingCart, PropertyBag);
                }
                return _logicProvider;
            }
        }
        private ILogicProvider _logicProvider;

        public string FirstOrderPackItemCode = GlobalUtilities.GetCurrentMarket().FirstOrderPackItemCode;
        #endregion

        #region Step 1 - Enrollment Configuration - Enroller Validate/Country Select
        public ActionResult Index()
        {
            ShoppingCart.Items.Clear();
            Exigo.PropertyBags.Update(ShoppingCart);
            return View();
        }

        [Route("{webalias}/choose-registration")]
        public ActionResult RegistrationLanding(string message = "")
        {
            ViewBag.Message = message;

            return View();
        }

        // If you have any issues with this, the web alias version needs to be used for UAT only and the Route without the webalias is for soft launch and live as of 2/18 - Mike M.
        [Route("backofficeenrollmentlanding")] // For soft launch
        [Route("{webalias}/backofficeenrollmentlanding")] // For live launch
        public ActionResult BackofficeEnrollmentLanding(int ownerID, string enroller, string sponsor)
        {
            dynamic Enroller;
            dynamic Sponsor;

            var enrollerwhereclause = "";
            var enrollerID = 0;
            if (int.TryParse(enroller, out enrollerID))
            {
                enrollerwhereclause = "AND c.CustomerID = " + enrollerID;
            }
            else
            {
                enrollerwhereclause = "AND c.LoginName = '" + enroller + "'";
            }
            using (var context = Exigo.Sql())
            {

                Enroller = context.Query(@"
                            Select c.CustomerID, c.FirstName, c.LastName, c.Company from Customers c
                            inner join UniLevelUpline uu
                            on c.CustomerID = uu.CustomerID
                            Where uu.UplineCustomerID = @id " + enrollerwhereclause + @"
                            and c.CustomerTypeID = @customerTypeID

                            union

                            Select  c.CustomerID, c.FirstName, c.LastName, c.Company from Customers c
                            inner join UniLevelDownline ud
                            on c.CustomerID = ud.CustomerID
                            Where ud.DownlineCustomerID = @id " + enrollerwhereclause + @"
                            and c.CustomerTypeID = @customerTypeID
                        ", new
                         {
                             id = ownerID,
                             customerTypeID = (int)CustomerTypes.Associate
                         }).FirstOrDefault();

                if (Enroller != null)
                {
                    if (enrollerID == 0)
                    {
                        enrollerID = Enroller.CustomerID;
                    }
                }
                else
                {
                    return RedirectToAction("EnrollmentConfiguration", new { message = "Enroller is invalid" });

                }

            }

            var sponsorrwhereclause = "";
            var sponsorID = 0;
            if (int.TryParse(sponsor, out sponsorID))
            {
                sponsorrwhereclause = "AND c.CustomerID = " + sponsorID;
            }
            else
            {
                sponsorrwhereclause = "AND c.LoginName = '" + sponsor + "'";
            }
            using (var context = Exigo.Sql())
            {
                Sponsor = context.Query(@"
                            Select  c.CustomerID, c.FirstName, c.LastName, c.Company from Customers c
                            inner join UniLevelDownline ud
                            on c.CustomerID = ud.CustomerID
                            Where ud.DownlineCustomerID = @id " + sponsorrwhereclause + @"
                            and c.CustomerTypeID = @customerTypeID
                        ", new
                        {
                            id = ownerID,
                            customerTypeID = (int)CustomerTypes.Associate
                        }).FirstOrDefault();

                if (Sponsor != null)
                {
                    if (sponsorID == 0)
                    {
                        sponsorID = Sponsor.CustomerID;

                    }
                }
                else
                {
                    return RedirectToAction("EnrollmentConfiguration", new { message = "Sponsor is invalid" });

                }
            }
            PropertyBag.SponsorID = sponsorID;
            PropertyBag.EnrollerID = enrollerID;

            // Set a value on the Property Bag to ensure that we know this was a back office user that started the Enrollment
            PropertyBag.IsBackofficeEnrollment = true;


            Exigo.PropertyBags.Update(PropertyBag);

            return RedirectToAction("Packs");
        }

        public ActionResult EnrollmentConfiguration(EnrollmentConfigurationViewModel enroller = null)
        {
            var model = new EnrollmentConfigurationViewModel();
            model.EnrollerID = Identity.Owner.CustomerID;
            model.SponsorID = GlobalSettings.ReplicatedSites.OrphanCustomerID;
            if (Request.QueryString["message"] != null)
            {
                ViewBag.Message = Request.QueryString["message"].ToString();
            }

            if (Request.HttpMethod == "GET")
            {
                if (!GlobalSettings.Globalization.HideForLive)
                {
                    // In this case, we already have an enroller set, so we are good to proceed to the next steps. This will need to change when multiple markets are available - Mike M.
                    if (PropertyBag.EnrollerID > 0 && PropertyBag.EnrollerID != GlobalSettings.ReplicatedSites.OrphanCustomerID)
                    {
                        return RedirectToAction("Packs");
                    }

                    // This will need to be removed when we introduce more markets than just US - Mike M.
                    if (model.EnrollerID != GlobalSettings.ReplicatedSites.OrphanCustomerID)
                    {
                        PropertyBag.EnrollerID = model.EnrollerID;
                        Exigo.PropertyBags.Update(PropertyBag);

                        return RedirectToAction("Packs");
                    }
                }

                return View(model);
            }
            else
            {
                // If the user has not chosen an Enroller, we need to return the view back to them so they can see an error message
                if (enroller.EnrollerID == GlobalSettings.ReplicatedSites.OrphanCustomerID)
                {
                    ViewBag.Error = ("Please choose an enroller before you continue your registration.");
                    return View(model);
                }
                if (enroller.SponsorID == GlobalSettings.ReplicatedSites.OrphanCustomerID)
                {
                    ViewBag.Error = ("Please choose a sponsor before you continue your registration.");
                    return View(model);
                }
                // FOR SOFTLAUNCH

                PropertyBag.SponsorID = enroller.SponsorID;
                PropertyBag.EnrollerID = enroller.EnrollerID;
                PropertyBag.SelectedMarket = (enroller.MarketName != null) ? enroller.MarketName : MarketName.UnitedStates;
                PropertyBag.EnrollmentType = enroller.SelectedEnrollmentType;
                Exigo.PropertyBags.Update(PropertyBag);

ReplicatedSite/Views/Home/About.cshtml
@model List<Country>
@{
    ViewBag.Title = "About";
}

<img src="http://placehold.it/1300x300" class="img-responsive">
<h2>About @Identity.Owner.FirstName</h2>
<p>Deleniti vituperatoribus pri ex. Homero fierent has at, harum laboramus nam at. Aliquip percipit lobortis in eam, apeirian imperdiet vituperata mea ei. Velit tation no ius, has reque denique phaedrum no. Nam tempor lucilius vituperatoribus no. Vim at partem inimicus disputationi, in vel docendi recteque dissentiunt, ad insolens antiopam eloquentiam has.</p>
<p>Habeo albucius splendide eam no. Facilisi pertinax necessitatibus cu sed, pri ad exerci doming. No mucius insolens cum, no velit clita consetetur nam. Noster sanctus at cum, id quodsi imperdiet contentiones vis.</p>
<p>Vix id cibo verterem electram, erant civibus signiferumque pro te, et cum altera detracto. Sit dicit eleifend id, et nihil mentitum deseruisse his. Hinc noster sit eu. Ut putant reprehendunt sea. Et duo fastidii menandri, viris saperet no qui. Ex ius meis scaevola molestiae, denique voluptaria id sit.</p>
<div class="row">
    <div class="col-sm-3"><img src="http://placehold.it/300x250" class="img-responsive"></div>
    <div class="col-sm-9">
        <p>Vis dolore invenire delicatissimi ea, pro an quidam habemus ponderum. Ne quo exerci regione mediocritatem, ad sea adhuc velit. Wisi facilis ad mei, tamquam probatus ex usu. Solum vivendo erroribus in pro. Eum harum efficiendi omittantur te, idque ludus iudicabit mei no, at illud veniam euripidis mel. Paulo ubique an quo.</p>
        <p>Illum elitr disputando eos id. Ius ea legimus epicuri complectitur, no senserit pertinacia delicatissimi per, posse audire moderatius mel in. Vim ne vidisse expetendis, maluisset torquatos pro ex. Ius ea graece accusamus, nostrum copiosae mel ea, volumus adipisci tincidunt mea no. Ea mei magna iisque dissentiunt.</p>
        <p>Deleniti vituperatoribus pri ex. Homero fierent has at, harum laboramus nam at. Aliquip percipit lobortis in eam, apeirian imperdiet vituperata mea ei. Velit tation no ius, has reque denique phaedrum no. Nam tempor lucilius vituperatoribus no. Vim at partem inimicus disputationi, in vel docendi recteque dissentiunt, ad insolens antiopam eloquentiam has.</p>
    </div>
</div>
<div class="space-30"></div>

ReplicatedSite/Views/Home/CompanyOverview.cshtml
@{
    ViewBag.Title = Resources.Common.CompanyOverview;
}

<input type="hidden" class="activenavigation" value="about" />

<div id="view-company-overview">
    <div class="space-40"></div>

    <h3>@ViewBag.Title</h3>

    <p>@Resources.Common.BonveraIsABusiness</p>
    <p>@Resources.Common.BonveraGivesYou</p>
    <p>@Resources.Common.BonveraWasDesigned</p>
    <p>@Resources.Common.WelcomeToBonvera</p>

    <div class="space-30"></div>
</div>

ReplicatedSite/Views/Home/ContactUs.cshtml
@{
    ViewBag.Title = "Contact Us";
}

<input type="hidden" class="activenavigation" value="contactus" />

<div id="view-contact-us">
    <h1>Coming Soon</h1>
</div>

ReplicatedSite/Views/Home/DistributorSearch.cshtml
@model DistributorSearch

@{
    ViewBag.Title = "Find a Distributor";

    var action = ViewContext.RouteData.Values["action"].ToString();
    var controller = ViewContext.RouteData.Values["controller"].ToString();
}

<div class="container" id="findDistributor" style="width: 90vw; margin: 0 auto;">
    <div id="results-modal-container"></div>
    <div class="row">
        <div class="col-sm-12">
            <h2 class="text-uppercase">Find a distributor or event </h2>
            <hr />
        </div>
        <div class="row">
            <div class="col-sm-8 col-sm-offset-1">
                <h3 class="text-muted">If you already know a Distributor:</h3>
            </div>
        </div>
    </div>

    <div class="row margin-0 form-group-container">
        <div class="col-sm-6 col-sm-offset-1">
            <div class="panel panel-primary">
                @*WebAddress*@
                <div class="panel-heading">
                    <h3 class="panel-title">Search by Distributor's Site Name</h3>
                </div>
                <div class="panel-body">
                    @*@Html.EditorForModel("Webalias")*@

                    <div class="row margin-5">
                        <div class="col-sm-9">
                            @Html.LabelFor(c => c.WebAlias, new { @class = "control-label" })
                        </div>
                    </div>
                    <div class="space-5"></div>

                    <div class="form row margin-5">
                        <div class="form-group col-sm-7">
                            @using (Ajax.BeginForm("getdistributors", controller, new AjaxOptions()
                {
                    //OnBegin = "distributorSearch.onBegin",
                    OnSuccess = "distributorSearch.onSuccess",
                    OnComplete = "distributorSearch.onComplete"
                }))
                            {
                                @Html.EditorForModel("Webalias")

                                <input type="hidden" name="@Html.NameFor(c => c.SearchTypeID)" id="@Html.IdFor(c => c.SearchTypeID)" value="@SearchType.webaddress" />
                            }
                        </div>
                        <div class="col-sm-3">
                            <button type="submit" class="btn btn-primary search" name="FindByDistributorID" id="id-search">Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
            <div class="panel panel-primary">
                @*DistributorID*@
                <div class="panel-heading">
                    <h3 class="panel-title">Search by Distributor's ID</h3>
                </div>
                <div class="panel-body">

                    @using (Ajax.BeginForm("getdistributors", controller, new AjaxOptions()
                {
                    //OnBegin = "distributorSearch.onBegin",
                    OnSuccess = "distributorSearch.onSuccess",
                    OnComplete = "distributorSearch.onComplete"
                }))
                    {
                        @Html.EditorForModel("DistributorID")

                        <input type="hidden" name="@Html.NameFor(c => c.SearchTypeID)" id="@Html.IdFor(c => c.SearchTypeID)" value="@SearchType.distributorID" />
                    }
                </div>
            </div>
        </div>

    </div>

    <div class="space-15"></div>

    @*DistributorInfo*@

    <div class="row form-group-container">
        <div class="col-sm-10 col-sm-offset-1">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Search by Name and State - Add the City and Zip (optional) for precise results</h3>
                </div>
                <div class="panel-body">
                    @using (Ajax.BeginForm("GetDistributors", controller, new AjaxOptions()
            {
                //OnBegin = "distributorSearch.onBegin",
                OnSuccess = "distributorSearch.onSuccess",
                OnComplete = "distributorSearch.onComplete"
            }))
                    {
                        @Html.EditorForModel("DesignerInfo")

                        <input type="hidden" name="@Html.NameFor(c => c.SearchTypeID)" id="@Html.IdFor(c => c.SearchTypeID)" value="@SearchType.distributorInfo" />
                    }
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <h3 class="text-muted">Don't know a distributor? Let us help you find one:</h3>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="alert alert-dismissable alert-danger" id="secondSearchMessage">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><i class="fa-close"></i></button>
                        <p>Try Searching for Distributors in your area by entering your zip code</p>
                    </div>
                    <h3 class="panel-title">Find a Distributor in Your Area</h3>
                </div>
                <div class="panel-body">
                    @using (Ajax.BeginForm("GetDistributors", controller, new AjaxOptions()
                {
                    //OnBegin = "distributorSearch.onBegin",
                    OnSuccess = "distributorSearch.onSuccess",
                    OnComplete = "distributorSearch.onComplete"
                }))
                    {
                        @Html.EditorForModel("ZipCode")

                        <input type="hidden" name="@Html.NameFor(c => c.SearchTypeID)" id="@Html.IdFor(c => c.SearchTypeID)" value="@SearchType.zipcode" />

                    }
                </div>
            </div>

        </div>

    </div>
    <div class="space-15"></div>

    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <h3 class="text-muted">Find an Event:</h3>
        </div>
    </div>

    <div class="space-15"></div>
    <div class="row margin-0 form-group-container">
        <div class="col-sm-6 col-sm-offset-1">
            <div class="panel panel-primary">
                @*Event Site*@
                <div class="panel-heading">
                    <h3 class="panel-title">Search by Event Site Name</h3>
                </div>
                <div class="panel-body">
                    @using (Ajax.BeginForm("GetEvents", controller, new AjaxOptions()
                {
                    //OnBegin = "distributorSearch.onBegin",
                    OnSuccess = "distributorSearch.onSuccess",
                }))
                    {
                        @Html.EditorForModel("EventSite")

                    }
                </div>
            </div>

            <div class="divider"></div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
            <div class="panel panel-primary">
                @*EventID*@
                <div class="panel-heading">
                    <h3 class="panel-title">Search by Event Code</h3>
                </div>
                <div class="panel-body">
                    @using (Ajax.BeginForm("GetEvents", controller, new AjaxOptions()
                {
                    //OnBegin = "distributorSearch.onBegin",
                    OnSuccess = "distributorSearch.onSuccess",
                }))
                    {
                        @Html.EditorForModel("EventID")

                    }
                </div>
            </div>
        </div>

    </div>
    <div class="space-50"></div>
    <div class="clearfix">&nbsp;</div>
</div>


<script>
    $("#noResults").hide();
    $("#secondSearchMessage").hide();

    require(["jquery", "bootstrap", "extensions", "pubsub"], function ($) {

        // Settings
        var context = "#findDistributor",
            $context = $(context),
            resultsModalUrl = "@Url.Action("quickshopmodal")";


        // Event Handlers
        function registerEventHandlers() {
            $('[data-role="search-field"]').on("keypress", function(e) {
                if (e.which == 13) {
                    e.preventDefault();
                    $('.search').click();
                }
            });

            $('#secondSearch').on('click', function() {
                $("#distributorSearchModal").modal('hide');
                $("#distributorSearchModal").on('hidden.bs.modal', function(e) {
                    $("#secondSearchMessage").show();
                    $('#customerZip', $context).focus();
                });
            });

            $('#search-results', $context).on("click", '[data-role="use-distributor"]', function() {
                var $activeRow = $(this).parents('.row:first'),
                    id = $('.id', $activeRow).html(),
                    name = $('.name', $activeRow).html(),
                    url = $("[data-url]", $activeRow).data("url");

                enroller = {
                    CustomerID: id,
                    FullName: name,
                    Url: url
                }

                $('#enrollerID').val(parseInt(enroller.CustomerID));

                window.trigger("registration.showchosenenrollerid", enroller);
                window.trigger("registration.enrolleridchosen");
            });

            $('[data-role="corporatesignup"]', $context).on('click', function() {

                window.trigger("registration.showchosenenrollerid", "corporate");
                window.trigger("registration.enrolleridchosen");
            });

            // Pubsub events
            window.on('registration.showchosenenrollerid', function(enroller) {
                actions.redirectToReferrer(enroller.Url);
            });
        }


        // Actions
        var actions = {
            redirectToReferrer: function(url) {
                if (url != "") {
                    window.location = url;
                }
            },


        };


// Initialization
        function init() {
            registerEventHandlers();
        }

        init();

    });


    var distributorSearch = (function() {
        require(["jquery", "toastr", "bootstrap", "extensions", "pubsub"], function($, toastr) {

            // Settings
            var context      = "#findDistributor",
                $context     = $(context),
                formSection  = $context.find('div[data-container]'),
                formButton   = formSection.find('button[data-role="search"]').attr('id'),
                $formContext = $("[data-container='" + formButton + "']");

            // Event Handlers
            function registerEventHandlers() {
                $('[data-role="search"]', $formContext).on('click', function(e) {
                    $(this).button('Searching');
                });
            }


            // Actions
            var actions = {
                onSuccess: function(response) {
                    var $submitbutton = $('[name="{0}"]'.format(response.action), $formContext);
                    var $root = helpers.getFormRoot($submitbutton);

                    if (response.success) {
                        $('[data-role="search"]', $formContext).button('reset');

                        $("#results-modal-container").html(response.html);
                        $("#results-modal-container .modal").modal();

                        if (@Model.BaseQuery.Count() == 0) {

                            $("#noResults").show();
                            $('.modal-title').hide();
                            $("#search-results").hide();
                            return;
                        }

                    } else {
                        $('[data-role="search"]', $formContext).button('reset');
                        console.log("message", response.message);
                        toastr.error("This search returned no results.", "We're sorry");
                        $("#noResults").show();
                        $('.modal-title').hide();
                        $("#search-results").hide();;
                    }
                },
                onComplete: function() {

                }
            };


            // Helpers
            var helpers = {
                getFormRoot: function($element) {
                    return $element.parents('.panel-body');
                }
            };


            // Initialization
            function init() {
                registerEventHandlers();
            }
            init();


            // Exports
            return {
                onSuccess: actions.onSuccess,
                //onBegin: actions.onBegin
            };

        });
    })();
</script>

ReplicatedSite/Views/Home/PreLaunchIndex.cshtml
@{
    Layout = "~/Views/Shared/_FullWidthLayout.cshtml";
    ViewBag.Title = "Shop. Save. Share.";
}

<input type="hidden" class="activenavigation" value="home" />

<div id="view-home-page">



    <!-- Shop Now -->
    <div class="container">
        <div class="row margin-0 text-center">
            <div class="space-70 hidden-sm hidden-xs"></div>
            <div class="space-40 visible-xs"></div>
            <h2>Welcome to Bonvera!</h2>
            <div style="max-width:650px; margin: 0 auto;">
                <p>
                    Bonvera’s vision is simple, straightforward and revolutionary:
                    create effortless access to everyday essentials while giving profits back to Associates.
                    Reward the people who supply, distribute and buy our products.
                    We call this unique concept of shopping “The Compensated Marketplace ™.”
                </p>
                <p>
                    Become a business owner and join Bonvera as an Independent Associate right now and get a jump start on building your business!
                    In March, we’ll introduce the “Retail Customer” and “Smart Shopper” options.
                    This is the Soft Launch Phase, and we have many exciting things in store for you as we roll out more products, services and features, so hold on tight!
                </p>
            </div>
            <div class="space-20"></div>

            <a href="@Url.Action("EnrollmentConfiguration", "Enrollment")" class="btn btn-primary">Click Here to join as Independent Associate.</a>

            <div class="space-30"></div>
            <a href="@GlobalSettings.Company.BaseBackofficeUrl" class="btn btn-primary">Click here if you already have an Account.</a>
            <div class="space-30"></div>
            <p>
                Shop. Save. Share.
                Bonvera
            </p>
        </div>
    </div>



</div>


@section scripts
{
    <script>
        require(["jquery", "bootstrap"], function ($) {
            function init() {
                // initiallize the carousel
                $('#product-banner').carousel();
            }
            init();
        });
    </script>
}