Backoffice/ViewModels/Shared/EditShippingAddressViewModel.cs
using ExigoService;
using System.Collections.Generic;

namespace Backoffice.ViewModels
{
    public class EditShippingAddressViewModel
    {
        public IEnumerable<ShippingAddress> Addresses { get; set; }
    }
}

Backoffice/Controllers/ShoppingController.cs
using Backoffice.Factories;
using Backoffice.Filters;
using Backoffice.Models;
using Backoffice.Providers;
using Backoffice.ViewModels;
using Backoffice.ViewModels.AutoOrders;
using Common;
using Common.Api.ExigoWebService;
using Common.Providers;
using Common.Services;
using ExigoService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Backoffice.Controllers
{
    [RoutePrefix("store")]
    [BackofficeAuthorize(RequiresLogin = true, ValidateSubscription = false)]
    [PreLaunchHide(AllowPreLaunch = false)]
    public class ShoppingController : Controller
    {
        #region Properties
        public string ShoppingCartName = "BackofficeShopping";

        public IOrderConfiguration OrderConfiguration = Identity.Current.Market.Configuration.Orders;
        public IOrderConfiguration AutoOrderConfiguration = Identity.Current.Market.Configuration.AutoOrders;

        public ShoppingCartItemsPropertyBag ShoppingCart
        {
            get
            {
                if (_shoppingCart == null)
                {
                    _shoppingCart = Exigo.PropertyBags.Get<ShoppingCartItemsPropertyBag>(ShoppingCartName + "Cart");
                }
                return _shoppingCart;
            }
        }
        private ShoppingCartItemsPropertyBag _shoppingCart;

        public ShoppingCartCheckoutPropertyBag PropertyBag
        {
            get
            {
                if (_propertyBag == null)
                {
                    _propertyBag = Exigo.PropertyBags.Get<ShoppingCartCheckoutPropertyBag>(ShoppingCartName + "PropertyBag");
                }
                return _propertyBag;
            }
        }
        private ShoppingCartCheckoutPropertyBag _propertyBag;

        public ILogicProvider LogicProvider
        {
            get
            {
                if (_logicProvider == null)
                {
                    _logicProvider = new ShoppingCartLogicProvider(this, ShoppingCart, PropertyBag);
                }
                return _logicProvider;
            }
        }
        private ILogicProvider _logicProvider;

        public int OrderPriceTypeID
        {
            get
            {
                var priceTy = PriceTypes.Wholesale;



                return priceTy;
            }
        }


        #endregion

        #region Category Landing
        [Route("shopping")]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OurProducts()
        {
            return View();
        }

        [Route("category")]
        public ActionResult Category()
        {
            return View();
        }
        #endregion

        #region Items/Cart
        [PreLaunchHide(AllowPreLaunch = true)]
        [Route("products/{parentCategoryKey?}/{subCategoryKey?}")]
        public ActionResult ItemList(string parentCategoryKey = null, string subCategoryKey = null)
        {
            var model = ShoppingViewModelFactory.Create<ItemListViewModel>(PropertyBag);
            if (!parentCategoryKey.IsEmpty()) model.parentCategoryKey = parentCategoryKey;
            if (!subCategoryKey.IsEmpty()) model.subCategoryKey = subCategoryKey;


            model.OrderConfiguration = OrderConfiguration;
            var webCategories = Exigo.GetItemCategories(OrderConfiguration.CategoryID);
            model.CurrentCategory = new ItemCategory();

            model.CategoryID = OrderConfiguration.CategoryID;

            if (parentCategoryKey.IsEmpty() && subCategoryKey.IsEmpty())
            {
                model.CategoryID = OrderConfiguration.FeaturedCategoryID;
                model.CurrentCategory = webCategories.Where(c => c.ItemCategoryID == model.CategoryID).FirstOrDefault();
            }

            if (!parentCategoryKey.IsEmpty())
            {
                model.CurrentCategory = webCategories.Where(c => c.ItemCategoryViewName.Equals(parentCategoryKey, StringComparison.InvariantCultureIgnoreCase)).FirstOrDefault();
                model.CategoryID = model.CurrentCategory.ItemCategoryID;
            }

            if (!subCategoryKey.IsEmpty())
            {
                var subcategory = model.CurrentCategory.Subcategories.FirstOrDefault(s => s.ItemCategoryViewName.Equals(subCategoryKey, StringComparison.InvariantCultureIgnoreCase));
                if (subcategory != null)
                {
                    model.CategoryID = subcategory.ItemCategoryID;
                }
            }

            model.Categories = webCategories;

            if (!parentCategoryKey.IsEmpty())
            {
                var mainCategories = model.Categories.Where(c => c.ItemCategoryID == model.CategoryID);

                if (mainCategories.Count() > 0)
                {
                    model.CurrentCategory = mainCategories.FirstOrDefault();
                }
                else
                {
                    foreach (var cat in model.Categories)
                    {
                        if (cat.Subcategories != null && cat.Subcategories.Any(s => s.ItemCategoryID == model.CategoryID))
                        {
                            model.CurrentCategory = cat.Subcategories.FirstOrDefault(s => s.ItemCategoryID == model.CategoryID);
                            model.CurrentCategory.ParentItemCategoryDescription = cat.ItemCategoryDescription;
                            model.CurrentCategory.ParentItemCategoryViewName = cat.ItemCategoryViewName;
                            model.CurrentCategory.ParentItemCategoryID = cat.ItemCategoryID;
                        }
                    }
                }
            }


            return View(model);
        }

        // Method to get items via ajax, based on the category selected on the ItemList page
        [PreLaunchHide(AllowPreLaunch = true)]
        [Route("GetItems")]
        public JsonNetResult GetItemList(int categoryId = 0, string search = "", SortByOptions sort = SortByOptions.AtoZ_Ascending)
        {
            var model = ShoppingViewModelFactory.Create<ItemListViewModel>(PropertyBag);
            var languageID = GlobalUtilities.GetSelectedExigoLanguageID();
            var hasSearchQuery = search.IsNotNullOrEmpty();
            
            model.OrderConfiguration = OrderConfiguration;

            //If the user is searching for something, then change the category id to "all products"
            categoryId = (hasSearchQuery) ? 6 : categoryId;

            //if its zero it means they havent landed on the page before, give em' the featured category (now Bonvera Private Label)
            if (categoryId == 0)
            {
                categoryId = model.OrderConfiguration.FeaturedCategoryID;
            }

            // Get the available products
            var itemsRequest = new ExigoService.GetItemsRequest
            {
                Configuration = OrderConfiguration,
                IncludeChildCategories = true,
                CategoryID = categoryId,
                LanguageID = languageID,
                PriceTypeID = OrderPriceTypeID
            };

            var itemsTask = Task.Factory.StartNew(() =>
            {
                model.Items = Exigo.GetItems(itemsRequest).ToList();
            });

            Task.WaitAll(itemsTask);
            //T.W. #84838 2/7/2017 IF othercheck is set to true than they are hidden/unavailable to purchase
            model.Items = model.Items.Where(c => c.OtherCheck1 == false).ToList();

            if (hasSearchQuery)
            {
                search = search.ToLower();
                var itemNameResults = model.Items.Where(c => c.ItemDescription.ToLower().Contains(search)).ToList();
                var shortDetailResults = model.Items = model.Items.Where(c => c.ShortDetail1.ToLower().Contains(search)).ToList();
                model.Items = itemNameResults.Union(shortDetailResults).ToList();
            }

            //sort the items gathered, by default alphabetically ascending
            switch (sort)
            {
                case SortByOptions.AtoZ_Descending:
                    model.Items = model.Items.OrderByDescending(x => x.ItemDescription).ToList();
                    break;
                case SortByOptions.BV_Ascending:
                    model.Items = model.Items.OrderBy(x => x.BV).ToList();
                    break;
                case SortByOptions.BV_Descending:
                    model.Items = model.Items.OrderByDescending(x => x.BV).ToList();
                    break;
                case SortByOptions.Price_Ascending:
                    model.Items = model.Items.OrderBy(x => x.Price).ToList();
                    break;
                case SortByOptions.Price_Descending:
                    model.Items = model.Items.OrderByDescending(x => x.Price).ToList();
                    break;
                default:
                    model.Items = model.Items.OrderBy(x => x.ItemDescription).ToList();
                    break;
            }

            model.CategoryID = categoryId;
            model.HasAutoOrderItems = ShoppingCart.HasAutoOrderItems();
            model.CurrentCategory = (Exigo.GetItemCategory(categoryId));

            var html = "";
            try
            {
                html = this.RenderPartialViewToString("Partials/Items/_ItemListModule", model);
            }
            catch (Exception e)
            {
                Console.Write(e);
            }
            return new JsonNetResult(new
            {
                success = true,
                html = html
            });
        }

        [HttpPost]
        public ActionResult ItemQuantity()
        {
            var count = 0;

            var items = ShoppingCart.Items.Where(c => c.ParentItemCode == null || c.ParentItemCode == "Parent").ToList();

            foreach (var item in items)
            {
                count += (int)item.Quantity;
            }

Backoffice/Views/Shared/_ErrorLayout.cshtml
@model System.Web.Mvc.HandleErrorInfo
@{
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
@section header { @RenderSection("header", required: false) }
@section scripts { @RenderSection("scripts", required: false) }


<div class="space-20"></div>
<div class="container container-expandable">
    @RenderBody()
</div>

<script>
    require(["jquery"], function ($) {
        $('body').append('<div id="__debug" style="width: 10px; height: 10px; position: absolute; bottom: 0; left: 0; z-index: 999999;" />');
        $('#__debug').on('click', function () {
            $('#__debuginfo').show();
        });
    });
</script>

@if (Model != null && (HttpContext.Current.Request.IsLocal || HttpContext.Current.IsDebuggingEnabled))
{
    <div class="container container-expandable" id="__debuginfo" style="display: none;">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Exception Details <br /><small class="text-muted">(This error is displaying because you are either on localhost or have debugging enabled)</small>
                </h3>
            </div>
            <div class="panel-body">
                <h2>
                    <span class="text-muted">
                        @ViewBag.StatusCode:
                    </span>
                    <span class="text-danger">
                        @Model.Exception.Message
                    </span>
                    @if (Model.Exception.InnerException != null)
                    { <br /><small class="text-muted">Inner Exception: @Model.Exception.InnerException.Message</small>
                    }
                </h2>
                <p>
                    <b>Controller:</b> @Model.ControllerName<br />
                    <b>Action:</b> @Model.ActionName
                </p>

                <pre>@Model.Exception.ToString()</pre>
            </div>
        </div>
    </div>
}

Backoffice/Views/Shared/_GlobalScripts.cshtml
<script>
    require(["jquery", "cookies", "ajax", "toastr", "app", "pubsub", "bootstrap", "extensions"], function ($, cookies, ajax, toastr) {

        var
            additemUrl = "@Url.Action("additemtocart", "shopping")",
            quickshopUrl = "@Url.Action("quickshopmodal", "shopping")",
            messageUsURL = "@Url.Action("messageus", "app")",
            getcartpreviewUrl = "@Url.Action("fetchcartpreview", "shopping")",
            getautoordermodalUrl = "@Url.Action("getautoordermodal", "shopping")",
            orderItemType = "@ShoppingCartItemType.Order",
            autoOrderItemType = "@ShoppingCartItemType.AutoOrder";

        var resources = {
            order: "@Resources.Common.Order",
            autoorder: "@Resources.Common.AutoOrder",
            itemAddedText: "@Resources.Common.HasBeenAddedToYour",
            autoOrderItemAddedText: "@Resources.Common.HasBeenAddedToYourAutoOrder"
        };

        var state = {
            modalActive: false
        };
        // Event Handlers
        function registerEventHandlers() {

            // Set defaults for toastr
            toastr.options.timeOut = 10000;

            // message us modal
            $('#message-us').on("click", function () {
                $('#message-us-modal').modal();
            });

            // message us submit
            $('#submit-message').on("click", function () {
                var form = $('#message-us-form').serializeObject(),
                    email = form.fromEmail,
                    subject = form.subject,
                    body = form.body,
                    emailNotEmpty = (/\S/.test(email)),
                    subjectNotEmpty = (/\S/.test(subject)),
                    bodyNotEmpty = (/\S/.test(body));

                // ensure the form is filled out completely before submitting
                if (emailNotEmpty == false || subjectNotEmpty == false || bodyNotEmpty == false) {
                    toastr.error("Please ensure all fields are filled out before submitting");
                    return;
                }

                ajax.json({
                    url: messageUsURL,
                    data: {
                        fromemail: email,
                        subject: subject,
                        body: body
                    },
                    success: function (response) {
                        if (response.success) {
                            $('#message-us-modal').modal("hide");
                            toastr.success("Your message has been sent!");
                        }
                        else {
                            toastr.error(response.message);
                        }
                    }
                });
            });

            $('[data-language]').on("click", function () {

                cookies.set('@GlobalSettings.Globalization.LanguageCookieName', $(this).data("language"), {
                    expires: new Date('@DateTime.Now.AddYears(1).ToShortDateString()'),
                    path: '/'
                });

                window.location = window.location;
            });

            // Auto Order Modal Logic
            window.on("cart.showautoordermodal", function (html) {

                // If we are passing in the cart html already, we do not need to get it from the server
                //L.G 8-2-2016 #78978: Added logic to prevent modal from appearing multiple times after the order is added to the cart
                if (html != null && html.length > 0) {
                    $("#addtocart-modalcontainer .modal-body").html("");
                    $("#addtocart-modalcontainer .modal-body").html(html);
                    $("#addtocart-modalcontainer .modal").modal("show");
                }
                else if (html == undefined) {
                    return false;
                }
                else {
                    actions.getAutoOrderModal();
                }
            });

            // Auto Order Modal Logic for Auto Order Manager
            window.on("autoordermanager.showautoordermodal", function (autoshipID) {
                actions.getAutoOrderModal(autoshipID);
            });

            $("body").on("click", "[data-quick-shop]", function () {

                if (state.modalActive == false) {
                    state.modalActive = true;

                    var itemcode = $(this).data("quick-shop");

                    ajax.json({
                        url: quickshopUrl,
                        data: { itemcode: itemcode },
                        success: function (response) {
                            if (response.success) {
                                $("#addtocart-modalcontainer .modal-body").html("");
                                $("#addtocart-modalcontainer .modal-body").html(response.html);
                                $("#addtocart-modalcontainer .modal").modal();
                            } else {
                                console.log("error fetching quick shop modal", response.message);
                            }
                        },
                        complete: function () {
                            $("#addtocart-modalcontainer .modal").on("hide.bs.modal", function () {
                                state.modalActive = false;
                            });
                        }
                    });
                }
            });
            $("body").on("click", "a[data-role='item.addtoorder']", function () {
                var $this = $(this),
                item = $this.parents(".item-fields").serializeObject();
                item.Type = $this.data("type");

                // Trigger the loading button
                $this.button('Adding');

                actions.addToCart(item);
            });
        }

        var actions = {
            addToCart: function (item) {

                ajax.json({
                    url: additemUrl,
                    data: {
                        item: item
                    },
                    success: function (response) {
                        if (response.success) {
                            var itemType = (item.Type == orderItemType) ? resources.order : resources.autoorder;

                            // Need a custom message for auto order items
                            if (item.Type == autoOrderItemType) {
                                toastr.success(resources.autoOrderItemAddedText.format(item.description));
                            } else {
                                toastr.success(resources.itemAddedText.format(item.description, itemType));

                            }

                            // Logic for First Order Pack shopping
                            if (response.isFirstOrderPack) {
                                $(".first-order-pack-container").hide();
                                $(".first-order-pack-added-message").show();
                                $(".modal").modal("hide");
                            }

                            //refresh the cart counter
                            actions.getCartPreview();

                            // Trigger the auto order modal if applicable
                            if (response.carttype == "autoorder") {
                                window.trigger("cart.showautoordermodal", response.html);

                            }
                        }
                    },
                    error: function (xhr) {
                        console.log("Add to cart failed", xhr);
                    },
                    complete: function () {
                        $("[data-role='item.addtoorder'][data-type='{0}'][data-itemcode='{1}']".format(item.Type, item.ItemCode)).button('reset');

                    }
                });
            },
            getAutoOrderModal: function (autoshipID) {
                ajax.json({
                    url: getautoordermodalUrl,
                    data: { autoshipID: autoshipID },
                    success: function (response) {
                        if (response.success) {
                            $("#addtocart-modalcontainer .modal-body").html("");
                            $("#addtocart-modalcontainer .modal-body").html(response.html);
                            $("#addtocart-modalcontainer .modal").modal();
                        } else {
                            console.log("showautoordermodal failed: ", response);
                        }
                    },
                    error: function (xhr, error, status) {
                        console.log("showautoordermodal failed: ", xhr);
                    }
                });
            },
            updateItemQuantity: function (item) {
                var $this = $(item),
                    quantity = $this.val(),
                    $parentContainer = $this.parents("[data-itemcode]").first(),
                    itemcode = $parentContainer.data("itemcode"),
                    priceEach = $this.data("price-each"),
                    $priceDisplayContainer = $parentContainer.find("[data-price-display]");

                if (quantity < 0) {
                    $this.val("0");
                    return;
                }

                // Set the price display of the items updated
                var price = priceEach * quantity;
                $priceDisplayContainer.html("$" + price.toFixed(2));
            },
            getCartPreview: function (total) {
                var $myCart = $("#my-cart");

                if (total != undefined) {
                    $("#my-cart").html(total);
                } else {
                    // Make sure that we have a cart module to show, else we dont fire this call for no reason
                    if ($myCart.length > 0) {
                        ajax.json({
                            url: "@Url.Action("GetCartItemQuantity", "Shopping")",
                            success: function (response) {
                                if (response.success) {
                                    $("#my-cart").html(response.count);
                                } else {
                                    console.log("error fetching quick shop modal", response.message);
                                }
                            }
                        });
                    }
                }
            },
        };
        // Initialization
        function init() {
            registerEventHandlers();

            actions.getCartPreview();

            $('[data-toggle="popover"]').popover();
        }

        init();
    });
</script>

Backoffice/Views/Shared/_PublicLayout.cshtml
@{
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
@section header { @RenderSection("header", required: false) }
@section scripts { @RenderSection("scripts", required: false) }

<main class="container container-expandable" id="site-content">
    @RenderBody()
</main>

Backoffice/Views/Shared/_ShoppingLayout.cshtml
@{
    Layout = "~/Views/Shared/_AuthenticatedLayout.cshtml";
}
@section styles { @RenderSection("styles", required: false) }
@section header { @RenderSection("header", required: false) }
@section scripts { @RenderSection("scripts", required: false) }
@section pagebanner { @RenderSection("pagebanner", required: false) }


@RenderSection("navigation", false)

    @RenderBody()